org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# NeoForge 1.21.1
minecraft_version=1.21.1
neoForgeVersion=21.1.74
neoFormVersion=20241027.145706

# Mod info
mod_id=lesrainstactical
mod_name=LesRaisins Tactical
mod_license=All-Rights-Reserved
mod_version=1.0.0
mod_group_id=me.xjqsh
mod_authors=xjqsh, LesRaisins Studio
mod_description=LesRaisins Armor and Tactical Equipment - Merged Mod for 1.21.1

# Dependencies versions
sable_companion_version=1.0.0
geckolibVersion=4.4.9
playerAnimatorVersion=1.0.2
clothConfigVersion=15.1.130
createVersion=6.0.9
parkourVersion=1.0.0
mixinExtrasVersion=1.1.0
