pluginManagement {
    repositories {
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'net.neoforged.moddev' version '1.7.82' apply false
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
}

rootProject.name = 'LesRaisinsTactical'